# ----------- CONFIGURABLE START -----------
title:            "GeoAI데이터학회"
description:      "학술대회 안내페이지"
url:              "http://www.gaidas2022.org"
baseurl:          ""
signoff:          "muan" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons
remote_theme :    Scribble Jekyll theme

links:
  - name:         Posts
    url:          /
    external:     false
  - name:         About me
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"
      
